### ISSUE TITLE
Warnings when used with WebPack

### ISSUE THREAD

**Issue by knmr** [linways/table-to-excel#12]
I'm getting warnings when I try to use this library with vue2 and webpack.

warning  in ./node_modules/@linways/table-to-excel/dist/tableToExcel.js
1:261-262 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

warning  in ./node_modules/@linways/table-to-excel/dist/tableToExcel.js
1:290-294 Critical dependency: the request of a dependency is an expression

**Comment by NguyenTheSon** [comment]
same issue

**Comment by rohithb** [comment]
Not sure what causes this warning. [Parcel](https://parceljs.org/) is used for bundling this library (not webpack). 
Will try to recreate this issue.

**Comment by joseluismurillorios** [comment]
Same here

![image](https://user-images.githubusercontent.com/11035303/60555041-8260a780-9cef-11e9-8359-c95a22430839.png)

**Comment by rohithb** [comment]
This warning is caused by some dynamic dependency in one of the libraries in this project.
As mentioned [here](https://github.com/benjamine/jsondiffpatch/issues/76#issuecomment-247323163), this can be fixed using a webpack config hack.
```
module: {
        exprContextCritical: false,
         ...
```
You can also use [`ContextReplacementPlugin`](https://webpack.js.org/plugins/context-replacement-plugin/) to fix this.
